### ISSUE TITLE
Store fonts locally

### ISSUE THREAD

**Issue by monodo** [InoxCommunication/ne-mobilite2030#1]
Fonts should not be loaded from remote server like in "http://fast.fonts.net/t/1.css?apiType=css&projectid=1da1d541-dd31-490f-9234-50a24f26c843" as this causes network error

**Comment by InoxCommunication** [comment]
The font files are strored locally. This file is tracker for the font licence. We cannot remove this link with the fonts.com server...

**Comment by monodo** [comment]
Ok...
